version: "3.2"

services:
  bbot-geebot:
    image: bbot-geebot
    build: .
    volumes: [".:/usr/src/app/"]
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    env_file: .env

    command: npm run chat:production
