version: "3.7"

services:
  bbot-geebot:
    image: bbot-geebot
    build: .
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    command: npm run chat
