version: "2.1"

services:
  bbot-geebot:
    image: bbot-geebot
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 --experimental-modules index.js
